config/routes.rb
Rails.application.routes.draw do
  root 'items#index'

  get '/signup' => 'customers#new'
  post '/customers' => 'customers#create'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get 'items/:page_number', to: 'items#index', as: 'items_per_page'

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_secure_password
  has_many :items

  validates :name, presence: true
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :customer

  validates :name, :price_in_cents, presence: true

  def self.for_customer(customer)
    where(customer_id: customer.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_customer
    @current_customer ||= Customer.find(session[:customer_id]) if session[:customer_id]
  end

  helper_method :current_customer
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

  def new
  end

  def create
    customer = Customer.new(customer_params)
    if customer.save
      session[:customer_id] = customer.id
      redirect_to root_path
    else
      redirect_to '/signup', notice: "Error. Please try again."
    end
  end

private

  def customer_params
    params.require(:customer).permit(:name, :address, :phone, :email, :password, :password_confirmation)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    if current_customer
      @items = Item.for_customer(current_customer)
      page_number = params[:page_number].to_i + 1
      limit_per_page = 25
      params[:max_num] = current_customer.items.length / limit_per_page
      @items = current_customer.items.limit(limit_per_page).offset(limit_per_page  * (page_number - 1))
      respond_to do |format|
      format.html { render template: 'items/index' }
      format.js
    end
    else
      redirect_to '/login'
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    customer = Customer.find_by_email(params[:email])
    if customer && customer.authenticate(params[:password])
      session[:customer_id] = customer.id
      redirect_to root_path
    else
      redirect_to '/login', notice: "Your log in info is not valid."
    end
  end

  def destroy
    session[:customer_id] = nil
    redirect_to '/login'
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/customers/new.html.erb
<h1>Sign up for a Grocery List!</h1>

<div>
<% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
  <% end %>
</div>
<div>
<%= form_for :customer, url: '/customers' do |f| %>
  <%= f.label :name %><%= f.text_field :name %>
  <%= f.label :email %><%= f.email_field :email %>
  <%= f.label :password %><%= f.password_field :password %>
  <%= f.label :password_confirmation %><%= f.password_field :password_confirmation %>

  <%= f.submit 'Sign Up' %>
<% end %>
</div>

app/views/items/_item_list.html.erb
<% pn = params[:page_number].to_i %>
<% mn = params[:max_num].to_i %>
<ul class="link_list">
  <% if pn < 1  %>
    <li></li>
  <% else %>
    <li><%= link_to "Previous", items_per_page_path(page_number: (pn - 1)) %></li>
  <% end %>
  <li><%= (pn + 1) %></li>
  <% if mn <= (pn + 1) %>
    <li></li>
  <% else %>
    <li><%= link_to "Next", items_per_page_path(page_number: (pn + 1)) %></li>
  <% end %>
</ul>
<ul class="item_list">
  <li class="header">
    <div class="customer_item_list"> <strong>Name</strong> </div>
    <div class="customer_item_list"> <strong>Category</strong> </div>
    <div class="customer_item_list"> <strong>Price</strong> </div>
  </li>
</ul>

<ul class = "item_list">
<% @items.each do |item| %>
  <span>
    <li>
      <div class="customer_item_list">
        <%= item.name %>
      </div>
      <div class="customer_item_list">
        <%= item.category %>
      </div>
      <div class="customer_item_list">
        <%= number_to_currency(item.price_in_cents / 100) %>
      </div>
    </li>
  </span>
<% end %>
</ul>

<ul class="link_list">
  <% if pn < 1  %>
    <li></li>
  <% else %>
    <li><%= link_to "Previous", items_per_page_path(page_number: (pn - 1)) %></li>
  <% end %>
  <li><%= (pn + 1) %></li>
  <% if mn <= (pn + 1) %>
    <li></li>
  <% else %>
    <li><%= link_to "Next", items_per_page_path(page_number: (pn + 1)) %></li>
  <% end %>
</ul>

app/views/items/index.html.erb
<h3>Your Grocery List</h3>

<% if current_customer.items.length < 1 %>
<h3> Sorry, but you have no items! </h3>
<% else %>
<div id="groceries">
  <%= render "item_list" %>
</div>
<% end %>

app/views/items/index.js.erb
$("#groceries").html("<%= escape_javascript(render("item_list")) %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GroceryData</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if current_customer %>
  Logged in as <%= current_customer.name %> | <%= link_to 'Log Out', '/logout' %>
<% else %>
  <%= link_to 'Log In', '/login' %> | <%= link_to 'Sign Up', '/signup' %>
<% end %>

<%= yield %>

</body>
</html>